name: Build Result
# template source: https://github.com/dockersamples/.github/blob/main/templates/call-docker-build.yaml

on:
  # we want pull requests so we can build(test) but not push to image registry
  push:
    branches:
      - 'main'
    # only build when important files change
    paths:
      - 'result/**'
      - '.github/workflows/call-docker-build-result.yaml'
  pull_request:
    branches:
      - 'main'
    # only build when important files change
    paths:
      - 'result/**'
      - '.github/workflows/call-docker-build-result.yaml'

jobs:
 build:
   runs-on: ubuntu-latest

   steps: 
   - name: checkout code
     uses: actions/checkout@v4

   - name: docker setup
     uses: docker/setup-docker-action@v4.3.0

   - name: docker login
     uses: docker/login-action@v3.5.0
     with:
       username: ${{secrets.docker_username}}
       password: ${{secrets.docker_password}}

   - name: build and push docker image
     uses: docker/build-push-action@v6.18.0
     with:
       context: src/product-catalog
       file: src/product-catalog/Dockerfile
       push: true
       tags: ${{ secrets.docker_username }}/product-catalog:${{github.run_id}}


     
   
